#! /usr/bin/env python
import sys
import requests

url = sys.argv[1]

payload = { 'lastname' : 'value' }
files = { 'firstname' : 'bar' }

#r = requests.post(url, data=multiPayload)
r = requests.post(url, data=payload, files=files)

print r.status_code
print r.text


