#! /usr/bin/env python
import sys
import requests

url = sys.argv[1]

mulitPayload = "files=dict(foo='bar')).textu'ok\n'"

payload = { 'key' : 'value' }
#r = requests.post(url, data=multiPayload)
r = requests.post(url, files=(('firstname','spam'),('lastname','eggs')))

print r.status_code
print r.text


